/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AppRouteImport } from './routes/_app'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as PublicStudbookRouteImport } from './routes/_public.studbook'
import { Route as AppTransferRouteImport } from './routes/_app.transfer'
import { Route as AppRegisterRouteImport } from './routes/_app.register'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppHorsesRouteImport } from './routes/_app.horses'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as PublicStudbookHorseIdRouteImport } from './routes/_public.studbook.$horseId'
import { Route as AppHorsesHorseIdRouteImport } from './routes/_app.horses.$horseId'
import { Route as AppAdminTransfersRouteImport } from './routes/_app.admin.transfers'
import { Route as AppAdminRegistrationsRouteImport } from './routes/_app.admin.registrations'
import { Route as AppAdminMembersRouteImport } from './routes/_app.admin.members'
import { Route as AppAdminHorsesRouteImport } from './routes/_app.admin.horses'
import { Route as AppAdminFeesRouteImport } from './routes/_app.admin.fees'
import { Route as AppTransferTransferIdPayRouteImport } from './routes/_app.transfer.$transferId.pay'
import { Route as AppRegisterRegistrationIdStatusRouteImport } from './routes/_app.register.$registrationId.status'
import { Route as AppRegisterRegistrationIdPayRouteImport } from './routes/_app.register.$registrationId.pay'
import { Route as AppAdminTransfersTransferIdRouteImport } from './routes/_app.admin.transfers.$transferId'
import { Route as AppAdminRegistrationsRegistrationIdRouteImport } from './routes/_app.admin.registrations.$registrationId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStudbookRoute = PublicStudbookRouteImport.update({
  id: '/studbook',
  path: '/studbook',
  getParentRoute: () => PublicRoute,
} as any)
const AppTransferRoute = AppTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppHorsesRoute = AppHorsesRouteImport.update({
  id: '/horses',
  path: '/horses',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const PublicStudbookHorseIdRoute = PublicStudbookHorseIdRouteImport.update({
  id: '/$horseId',
  path: '/$horseId',
  getParentRoute: () => PublicStudbookRoute,
} as any)
const AppHorsesHorseIdRoute = AppHorsesHorseIdRouteImport.update({
  id: '/$horseId',
  path: '/$horseId',
  getParentRoute: () => AppHorsesRoute,
} as any)
const AppAdminTransfersRoute = AppAdminTransfersRouteImport.update({
  id: '/transfers',
  path: '/transfers',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminRegistrationsRoute = AppAdminRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminMembersRoute = AppAdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminHorsesRoute = AppAdminHorsesRouteImport.update({
  id: '/horses',
  path: '/horses',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminFeesRoute = AppAdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppTransferTransferIdPayRoute =
  AppTransferTransferIdPayRouteImport.update({
    id: '/$transferId/pay',
    path: '/$transferId/pay',
    getParentRoute: () => AppTransferRoute,
  } as any)
const AppRegisterRegistrationIdStatusRoute =
  AppRegisterRegistrationIdStatusRouteImport.update({
    id: '/$registrationId/status',
    path: '/$registrationId/status',
    getParentRoute: () => AppRegisterRoute,
  } as any)
const AppRegisterRegistrationIdPayRoute =
  AppRegisterRegistrationIdPayRouteImport.update({
    id: '/$registrationId/pay',
    path: '/$registrationId/pay',
    getParentRoute: () => AppRegisterRoute,
  } as any)
const AppAdminTransfersTransferIdRoute =
  AppAdminTransfersTransferIdRouteImport.update({
    id: '/$transferId',
    path: '/$transferId',
    getParentRoute: () => AppAdminTransfersRoute,
  } as any)
const AppAdminRegistrationsRegistrationIdRoute =
  AppAdminRegistrationsRegistrationIdRouteImport.update({
    id: '/$registrationId',
    path: '/$registrationId',
    getParentRoute: () => AppAdminRegistrationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/horses': typeof AppHorsesRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/register': typeof AppRegisterRouteWithChildren
  '/transfer': typeof AppTransferRouteWithChildren
  '/studbook': typeof PublicStudbookRouteWithChildren
  '/admin/fees': typeof AppAdminFeesRoute
  '/admin/horses': typeof AppAdminHorsesRoute
  '/admin/members': typeof AppAdminMembersRoute
  '/admin/registrations': typeof AppAdminRegistrationsRouteWithChildren
  '/admin/transfers': typeof AppAdminTransfersRouteWithChildren
  '/horses/$horseId': typeof AppHorsesHorseIdRoute
  '/studbook/$horseId': typeof PublicStudbookHorseIdRoute
  '/admin/registrations/$registrationId': typeof AppAdminRegistrationsRegistrationIdRoute
  '/admin/transfers/$transferId': typeof AppAdminTransfersTransferIdRoute
  '/register/$registrationId/pay': typeof AppRegisterRegistrationIdPayRoute
  '/register/$registrationId/status': typeof AppRegisterRegistrationIdStatusRoute
  '/transfer/$transferId/pay': typeof AppTransferTransferIdPayRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/chat': typeof AppChatRoute
  '/dashboard': typeof AppDashboardRoute
  '/horses': typeof AppHorsesRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/profile': typeof AppProfileRoute
  '/register': typeof AppRegisterRouteWithChildren
  '/transfer': typeof AppTransferRouteWithChildren
  '/studbook': typeof PublicStudbookRouteWithChildren
  '/admin/fees': typeof AppAdminFeesRoute
  '/admin/horses': typeof AppAdminHorsesRoute
  '/admin/members': typeof AppAdminMembersRoute
  '/admin/registrations': typeof AppAdminRegistrationsRouteWithChildren
  '/admin/transfers': typeof AppAdminTransfersRouteWithChildren
  '/horses/$horseId': typeof AppHorsesHorseIdRoute
  '/studbook/$horseId': typeof PublicStudbookHorseIdRoute
  '/admin/registrations/$registrationId': typeof AppAdminRegistrationsRegistrationIdRoute
  '/admin/transfers/$transferId': typeof AppAdminTransfersTransferIdRoute
  '/register/$registrationId/pay': typeof AppRegisterRegistrationIdPayRoute
  '/register/$registrationId/status': typeof AppRegisterRegistrationIdStatusRoute
  '/transfer/$transferId/pay': typeof AppTransferTransferIdPayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/chat': typeof AppChatRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/horses': typeof AppHorsesRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/register': typeof AppRegisterRouteWithChildren
  '/_app/transfer': typeof AppTransferRouteWithChildren
  '/_public/studbook': typeof PublicStudbookRouteWithChildren
  '/_public/': typeof PublicIndexRoute
  '/_app/admin/fees': typeof AppAdminFeesRoute
  '/_app/admin/horses': typeof AppAdminHorsesRoute
  '/_app/admin/members': typeof AppAdminMembersRoute
  '/_app/admin/registrations': typeof AppAdminRegistrationsRouteWithChildren
  '/_app/admin/transfers': typeof AppAdminTransfersRouteWithChildren
  '/_app/horses/$horseId': typeof AppHorsesHorseIdRoute
  '/_public/studbook/$horseId': typeof PublicStudbookHorseIdRoute
  '/_app/admin/registrations/$registrationId': typeof AppAdminRegistrationsRegistrationIdRoute
  '/_app/admin/transfers/$transferId': typeof AppAdminTransfersTransferIdRoute
  '/_app/register/$registrationId/pay': typeof AppRegisterRegistrationIdPayRoute
  '/_app/register/$registrationId/status': typeof AppRegisterRegistrationIdStatusRoute
  '/_app/transfer/$transferId/pay': typeof AppTransferTransferIdPayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/horses'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/transfer'
    | '/studbook'
    | '/admin/fees'
    | '/admin/horses'
    | '/admin/members'
    | '/admin/registrations'
    | '/admin/transfers'
    | '/horses/$horseId'
    | '/studbook/$horseId'
    | '/admin/registrations/$registrationId'
    | '/admin/transfers/$transferId'
    | '/register/$registrationId/pay'
    | '/register/$registrationId/status'
    | '/transfer/$transferId/pay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/horses'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/transfer'
    | '/studbook'
    | '/admin/fees'
    | '/admin/horses'
    | '/admin/members'
    | '/admin/registrations'
    | '/admin/transfers'
    | '/horses/$horseId'
    | '/studbook/$horseId'
    | '/admin/registrations/$registrationId'
    | '/admin/transfers/$transferId'
    | '/register/$registrationId/pay'
    | '/register/$registrationId/status'
    | '/transfer/$transferId/pay'
  id:
    | '__root__'
    | '/_app'
    | '/_public'
    | '/login'
    | '/signup'
    | '/_app/admin'
    | '/_app/chat'
    | '/_app/dashboard'
    | '/_app/horses'
    | '/_app/notifications'
    | '/_app/profile'
    | '/_app/register'
    | '/_app/transfer'
    | '/_public/studbook'
    | '/_public/'
    | '/_app/admin/fees'
    | '/_app/admin/horses'
    | '/_app/admin/members'
    | '/_app/admin/registrations'
    | '/_app/admin/transfers'
    | '/_app/horses/$horseId'
    | '/_public/studbook/$horseId'
    | '/_app/admin/registrations/$registrationId'
    | '/_app/admin/transfers/$transferId'
    | '/_app/register/$registrationId/pay'
    | '/_app/register/$registrationId/status'
    | '/_app/transfer/$transferId/pay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/studbook': {
      id: '/_public/studbook'
      path: '/studbook'
      fullPath: '/studbook'
      preLoaderRoute: typeof PublicStudbookRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_app/transfer': {
      id: '/_app/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof AppTransferRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/horses': {
      id: '/_app/horses'
      path: '/horses'
      fullPath: '/horses'
      preLoaderRoute: typeof AppHorsesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_public/studbook/$horseId': {
      id: '/_public/studbook/$horseId'
      path: '/$horseId'
      fullPath: '/studbook/$horseId'
      preLoaderRoute: typeof PublicStudbookHorseIdRouteImport
      parentRoute: typeof PublicStudbookRoute
    }
    '/_app/horses/$horseId': {
      id: '/_app/horses/$horseId'
      path: '/$horseId'
      fullPath: '/horses/$horseId'
      preLoaderRoute: typeof AppHorsesHorseIdRouteImport
      parentRoute: typeof AppHorsesRoute
    }
    '/_app/admin/transfers': {
      id: '/_app/admin/transfers'
      path: '/transfers'
      fullPath: '/admin/transfers'
      preLoaderRoute: typeof AppAdminTransfersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/registrations': {
      id: '/_app/admin/registrations'
      path: '/registrations'
      fullPath: '/admin/registrations'
      preLoaderRoute: typeof AppAdminRegistrationsRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/members': {
      id: '/_app/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AppAdminMembersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/horses': {
      id: '/_app/admin/horses'
      path: '/horses'
      fullPath: '/admin/horses'
      preLoaderRoute: typeof AppAdminHorsesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/fees': {
      id: '/_app/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AppAdminFeesRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/transfer/$transferId/pay': {
      id: '/_app/transfer/$transferId/pay'
      path: '/$transferId/pay'
      fullPath: '/transfer/$transferId/pay'
      preLoaderRoute: typeof AppTransferTransferIdPayRouteImport
      parentRoute: typeof AppTransferRoute
    }
    '/_app/register/$registrationId/status': {
      id: '/_app/register/$registrationId/status'
      path: '/$registrationId/status'
      fullPath: '/register/$registrationId/status'
      preLoaderRoute: typeof AppRegisterRegistrationIdStatusRouteImport
      parentRoute: typeof AppRegisterRoute
    }
    '/_app/register/$registrationId/pay': {
      id: '/_app/register/$registrationId/pay'
      path: '/$registrationId/pay'
      fullPath: '/register/$registrationId/pay'
      preLoaderRoute: typeof AppRegisterRegistrationIdPayRouteImport
      parentRoute: typeof AppRegisterRoute
    }
    '/_app/admin/transfers/$transferId': {
      id: '/_app/admin/transfers/$transferId'
      path: '/$transferId'
      fullPath: '/admin/transfers/$transferId'
      preLoaderRoute: typeof AppAdminTransfersTransferIdRouteImport
      parentRoute: typeof AppAdminTransfersRoute
    }
    '/_app/admin/registrations/$registrationId': {
      id: '/_app/admin/registrations/$registrationId'
      path: '/$registrationId'
      fullPath: '/admin/registrations/$registrationId'
      preLoaderRoute: typeof AppAdminRegistrationsRegistrationIdRouteImport
      parentRoute: typeof AppAdminRegistrationsRoute
    }
  }
}

interface AppAdminRegistrationsRouteChildren {
  AppAdminRegistrationsRegistrationIdRoute: typeof AppAdminRegistrationsRegistrationIdRoute
}

const AppAdminRegistrationsRouteChildren: AppAdminRegistrationsRouteChildren = {
  AppAdminRegistrationsRegistrationIdRoute:
    AppAdminRegistrationsRegistrationIdRoute,
}

const AppAdminRegistrationsRouteWithChildren =
  AppAdminRegistrationsRoute._addFileChildren(
    AppAdminRegistrationsRouteChildren,
  )

interface AppAdminTransfersRouteChildren {
  AppAdminTransfersTransferIdRoute: typeof AppAdminTransfersTransferIdRoute
}

const AppAdminTransfersRouteChildren: AppAdminTransfersRouteChildren = {
  AppAdminTransfersTransferIdRoute: AppAdminTransfersTransferIdRoute,
}

const AppAdminTransfersRouteWithChildren =
  AppAdminTransfersRoute._addFileChildren(AppAdminTransfersRouteChildren)

interface AppAdminRouteChildren {
  AppAdminFeesRoute: typeof AppAdminFeesRoute
  AppAdminHorsesRoute: typeof AppAdminHorsesRoute
  AppAdminMembersRoute: typeof AppAdminMembersRoute
  AppAdminRegistrationsRoute: typeof AppAdminRegistrationsRouteWithChildren
  AppAdminTransfersRoute: typeof AppAdminTransfersRouteWithChildren
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminFeesRoute: AppAdminFeesRoute,
  AppAdminHorsesRoute: AppAdminHorsesRoute,
  AppAdminMembersRoute: AppAdminMembersRoute,
  AppAdminRegistrationsRoute: AppAdminRegistrationsRouteWithChildren,
  AppAdminTransfersRoute: AppAdminTransfersRouteWithChildren,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppHorsesRouteChildren {
  AppHorsesHorseIdRoute: typeof AppHorsesHorseIdRoute
}

const AppHorsesRouteChildren: AppHorsesRouteChildren = {
  AppHorsesHorseIdRoute: AppHorsesHorseIdRoute,
}

const AppHorsesRouteWithChildren = AppHorsesRoute._addFileChildren(
  AppHorsesRouteChildren,
)

interface AppRegisterRouteChildren {
  AppRegisterRegistrationIdPayRoute: typeof AppRegisterRegistrationIdPayRoute
  AppRegisterRegistrationIdStatusRoute: typeof AppRegisterRegistrationIdStatusRoute
}

const AppRegisterRouteChildren: AppRegisterRouteChildren = {
  AppRegisterRegistrationIdPayRoute: AppRegisterRegistrationIdPayRoute,
  AppRegisterRegistrationIdStatusRoute: AppRegisterRegistrationIdStatusRoute,
}

const AppRegisterRouteWithChildren = AppRegisterRoute._addFileChildren(
  AppRegisterRouteChildren,
)

interface AppTransferRouteChildren {
  AppTransferTransferIdPayRoute: typeof AppTransferTransferIdPayRoute
}

const AppTransferRouteChildren: AppTransferRouteChildren = {
  AppTransferTransferIdPayRoute: AppTransferTransferIdPayRoute,
}

const AppTransferRouteWithChildren = AppTransferRoute._addFileChildren(
  AppTransferRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppChatRoute: typeof AppChatRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHorsesRoute: typeof AppHorsesRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppRegisterRoute: typeof AppRegisterRouteWithChildren
  AppTransferRoute: typeof AppTransferRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppChatRoute: AppChatRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHorsesRoute: AppHorsesRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppRegisterRoute: AppRegisterRouteWithChildren,
  AppTransferRoute: AppTransferRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PublicStudbookRouteChildren {
  PublicStudbookHorseIdRoute: typeof PublicStudbookHorseIdRoute
}

const PublicStudbookRouteChildren: PublicStudbookRouteChildren = {
  PublicStudbookHorseIdRoute: PublicStudbookHorseIdRoute,
}

const PublicStudbookRouteWithChildren = PublicStudbookRoute._addFileChildren(
  PublicStudbookRouteChildren,
)

interface PublicRouteChildren {
  PublicStudbookRoute: typeof PublicStudbookRouteWithChildren
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicStudbookRoute: PublicStudbookRouteWithChildren,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
